
CREATE TABLE inv_tbl_customer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    updated_date  TIMESTAMP WITHOUT TIME ZONE,
    address       VARCHAR(255),
    email_address VARCHAR(255)                            NOT NULL,
    full_name     VARCHAR(255),
    phone_number  VARCHAR(255)                            NOT NULL,
    CONSTRAINT inv_tbl_customer_pkey PRIMARY KEY (id)
);

CREATE TABLE inv_tbl_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    order_number VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255),
    customer_id  BIGINT,
    CONSTRAINT inv_tbl_order_pkey PRIMARY KEY (id)
);

CREATE TABLE inv_tbl_order_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE,
    updated_date      TIMESTAMP WITHOUT TIME ZONE,
    order_item_number VARCHAR(255)                            NOT NULL,
    quantity          BIGINT,
    status            VARCHAR(255),
    total_amount      numeric(19, 2),
    unit_price        numeric(19, 2),
    order_id          BIGINT,
    product_id        BIGINT,
    CONSTRAINT inv_tbl_order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE inv_tbl_product
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                        TIMESTAMP WITHOUT TIME ZONE,
    updated_date                        TIMESTAMP WITHOUT TIME ZONE,
    allowable_minimum_quantity_in_stock INTEGER DEFAULT 0                       NOT NULL,
    code                                VARCHAR(255)                            NOT NULL,
    description                         TEXT,
    general_discount                    numeric(19, 2),
    name                                VARCHAR(255)                            NOT NULL,
    price                               numeric(19, 2)                          NOT NULL,
    quantity_in_stock                   BIGINT  DEFAULT 0                       NOT NULL,
    status                              VARCHAR(255),
    CONSTRAINT inv_tbl_product_pkey PRIMARY KEY (id)
);

ALTER TABLE inv_tbl_customer
    ADD CONSTRAINT uk_jgvtmgiir5fw0y8bwl6wxpfqr UNIQUE (phone_number);

ALTER TABLE inv_tbl_customer
    ADD CONSTRAINT uk_mxhvi55ho5po2qex6k30s4gdh UNIQUE (email_address);

ALTER TABLE inv_tbl_order
    ADD CONSTRAINT uk_477llisn5u5wqg5dkou81d8m6 UNIQUE (order_number);

ALTER TABLE inv_tbl_order_items
    ADD CONSTRAINT uk_adsix3lbd1oporop70lnnvjjw UNIQUE (order_item_number);

ALTER TABLE inv_tbl_product
    ADD CONSTRAINT uk_i1cvwv5jfbvvy75n1ugcjnq0v UNIQUE (code);

ALTER TABLE inv_tbl_product
    ADD CONSTRAINT uk_tiswbc2tebl2bre58nc0kmtku UNIQUE (name);

ALTER TABLE inv_tbl_order
    ADD CONSTRAINT fk4qvy0h85odeo4ufomtiuun4to FOREIGN KEY (customer_id) REFERENCES inv_tbl_customer (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE inv_tbl_order_items
    ADD CONSTRAINT fkatpe427sy5lyeqbhfky705xo6 FOREIGN KEY (product_id) REFERENCES inv_tbl_product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE inv_tbl_order_items
    ADD CONSTRAINT fkj153365thbnee0yli3gripo6r FOREIGN KEY (order_id) REFERENCES inv_tbl_order (id) ON UPDATE NO ACTION ON DELETE NO ACTION;